In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]
my_array1 = np.array(my_list1)

In [3]:
my_array1

array([1, 2, 3, 4])

### what happens if we try to create funky shaped arrays?

In [6]:
my_list2 = [5,9.0,25]
my_array2 = np.array([my_list1, my_list2])
my_array2

array([[1, 2, 3, 4], [5, 9.0, 25]], dtype=object)

In [7]:
my_array2.shape

(2,)

### We can also create some standard arrays

In [9]:
np.zeros([4,4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [10]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [11]:
np.eye(7)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [18]:
full = np.arange(0,25,1)
full = np.reshape(full,[5,5])
full

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Element-wise operations

In [19]:
2*full

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [22]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
print a1.shape
a1*a1

(2, 4)


array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [23]:
a1**3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]])

In [24]:
a1+a1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

### slicing fun!

looks like we pass arrays around as pointers, so be careful with naming arrays...

In [25]:
full2 = full
full2[0:2] = 777
full

array([[777, 777, 777, 777, 777],
       [777, 777, 777, 777, 777],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [26]:
full = np.arange(0,25,1)
full = np.reshape(full,[5,5])
full

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
full3 = np.copy(full)
full3[2:,1:4] = 679
full3

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10, 679, 679, 679,  14],
       [ 15, 679, 679, 679,  19],
       [ 20, 679, 679, 679,  24]])

In [47]:
full

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

So arrays are indexed as A\[row\]\[column\], and one can use the colon operator to subset things.

In [32]:
full[0][3]

3

In [33]:
full[1][2:]

array([7, 8, 9])

The weird thing is that if you want to slice the array in two-dimensions it's in one bracket.

In [31]:
full2[1:3,2:]

array([[777, 777, 777],
       [ 12,  13,  14]])

You can also slice in steps!

In [36]:
full[2][0::2]

array([10, 12, 14])

### Transposition and matrix multiply

In [50]:
full

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
full.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [52]:
np.dot(full.T, full)

array([[ 750,  800,  850,  900,  950],
       [ 800,  855,  910,  965, 1020],
       [ 850,  910,  970, 1030, 1090],
       [ 900,  965, 1030, 1095, 1160],
       [ 950, 1020, 1090, 1160, 1230]])

As usual multiplication of matrices is not commutative

In [54]:
np.dot(full, full.T)

array([[  30,   80,  130,  180,  230],
       [  80,  255,  430,  605,  780],
       [ 130,  430,  730, 1030, 1330],
       [ 180,  605, 1030, 1455, 1880],
       [ 230,  780, 1330, 1880, 2430]])

Note that there is a numpy inner which for 1-D arrays is the same np.dot

### Universal and binary functions
These are all the functions that can be applied to each element in an array. The full list can be found [here](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

In [55]:
np.sin(full)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [57]:
np.sqrt(full)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ],
       [ 3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739],
       [ 3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894],
       [ 4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949]])

Binary functions compare two arrays element-wise

In [59]:
np.maximum(full, full2-25)

array([[752, 752, 752, 752, 752],
       [752, 752, 752, 752, 752],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])