In [1]:
import numpy as np

### Let's save a single array in a file

In [3]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
np.save('samplearr', arr)

In [8]:
arr2 = np.load('samplearr.npy')
arr2[4:7] = 35
arr2

array([ 0,  1,  2,  3, 35, 35, 35,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Save more than one array

In [13]:
np.savez('twoarrays.npz',x=arr, y = arr2)

In [16]:
saved_arrays = np.load('twoarrays.npz')
saved_arrays['x']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
saved_arrays['y']

array([ 0,  1,  2,  3, 35, 35, 35,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### We can also export as delimited text file

In [21]:
np.savetxt('array.txt', arr2, delimiter=';')
np.loadtxt('array.txt', delimiter = ';')

array([  0.,   1.,   2.,   3.,  35.,  35.,  35.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.])